name: Docker publish apm to docker.io

on:
  push:
    paths:
      - '.github/workflows/docker-apm.yml'
      - 'packages/**'
      - 'docker-bin/**'
      - 'bin/**'
      - 'package-apm.json'
      - 'pnpm-*.yaml'
      - '.dockerignore'
      - 'docker-compose.yml'
      - 'Dockerfile-apm'
      - 'config.yaml'
      - 'abappm/**'
    branches:
      - 'apm'

permissions:
  contents: read

concurrency:
  group: apm-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.repository == 'mbtools/verdaccio'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare Docker Image Tags
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: abappm/registry
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'apm') }}
            type=sha

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-apm
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
